name: egmde-confined-desktop
version: egmde
version-script: |
  LANG=C apt-cache policy libmiral-dev | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/0.3-\1/p'
summary: A minimal Mir based desktop with some test applications
description: A minimal Mir based desktop with some test applications
confinement: strict
grade: stable
base: core18

apps:
  egmde:
    command: bin/run-egmde
    daemon: simple
    slots:
      - mir
      - wayland
    plugs:
      - opengl
    environment:
      EGMDE_FONT: $SNAP/usr/share/fonts/truetype/freefont/FreeSansBold.ttf
      LC_ALL: C.UTF-8
      #      XDG_RUNTIME_DIR: /run/user/0
      XDG_CONFIG_HOME: $SNAP_DATA
      XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
      XCURSOR_PATH:    $SNAP/icons
      # Prep for Mir
      MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
      MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
      # Prep for Qt wayland
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/
      # Prep EGL
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d

parts:
  egmde:
    plugin: cmake
    source: https://github.com/AlanGriffiths/egmde.git
    build-packages:
    - pkg-config
    - libmiral-dev
    - libboost-filesystem-dev
    - libfreetype6-dev
    stage-packages:
    - fonts-freefont-ttf
    - mir-graphics-drivers-desktop
    - libmiral3

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]
    organize:
      usr/share/icons/DMZ-White: icons/default
    prime:
     - icons/default

  glue:
    plugin: dump
    source: glue

  games:
    plugin: nil
    stage-packages:
      # SDL & working
    - neverball
    - neverputt
    - starfighter
